# Numpy Tutorial

## The Basics (Creating arrays,Shape, Size, Data Type)

In [6]:
import numpy as np
import sys

In [49]:
a= np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [47]:
b = np.array([[9,8,7],[6,5,4],[0,0,0]])
print(b)

[[9 8 7]
 [6 5 4]
 [0 0 0]]


In [35]:
c = np.array([[[9.0,8.0,7.0],[6.0,5.0,4.0],[0.0,0.0,0.0]],[[7.0,9.0,8.0],[0.0,0.0,0.0],[1.0,2.0,3.0]],[[4.0,3.0,2.0],[1.0,7.0,5.0],[6.0,6.0,6.0]]])
print(c)

[[[9. 8. 7.]
  [6. 5. 4.]
  [0. 0. 0.]]

 [[7. 9. 8.]
  [0. 0. 0.]
  [1. 2. 3.]]

 [[4. 3. 2.]
  [1. 7. 5.]
  [6. 6. 6.]]]


In [225]:
print("\n# Get Dimensions")
print(a.ndim)
print(b.ndim)
print(c.ndim)
print("\n#Get Shape")
print(a.shape)
print(b.shape)
print(c.shape)
print("\n#Get Type")
print(a.dtype)
print(b.dtype)
print(c.dtype)
print("\n#Get Element Size")
print(a.itemsize)
print(b.itemsize)
print(c.itemsize)
print("\n#Get No. of Elements")
print(a.size)
print(b.size)
print(c.size)
print("\n#Get Total Size")
print(a.size*a.itemsize)
print(b.size*b.itemsize)
print(c.size*c.itemsize)
print("\n#Get Total Size in Single Command")
print(a.nbytes)
print(b.nbytes)
print(c.nbytes)


# Get Dimensions
2
2
2

#Get Shape
(2, 9)
(2, 9)
(2, 9)

#Get Type
int64
int64
int64

#Get Element Size
8
8
8

#Get No. of Elements
18
18
18

#Get Total Size
144
144
144

#Get Total Size in Single Command
144
144
144


## Accesing/Changing Elements

In [76]:
a = np.array([[1,2,3,4,5,6,7,8,9],[0,9,8,7,6,5,4,3,2]])
print(a)

[[1 2 3 4 5 6 7 8 9]
 [0 9 8 7 6 5 4 3 2]]


In [57]:
# To get 8, use row and column index
a[0,7]
# also can give reverse identification
a[0,-2]

8

In [64]:
# Getting specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
# Getting specific column
a[:,0]

array([1, 0])

In [77]:
#Chaning elements
print(a)
a[0,7]=15
print(a)
a[:,3]=13
print(a)


[[1 2 3 4 5 6 7 8 9]
 [0 9 8 7 6 5 4 3 2]]
[[ 1  2  3  4  5  6  7 15  9]
 [ 0  9  8  7  6  5  4  3  2]]
[[ 1  2  3 13  5  6  7 15  9]
 [ 0  9  8 13  6  5  4  3  2]]


In [86]:
b= np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [87]:
# Get specific element in 3D array (work outside in)

b[0,1,:]

array([3, 4])

In [88]:
print(b)
b[1,:,:] = ([[9,8],[7,6]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [3 4]]

 [[9 8]
  [7 6]]]


## Initializing Different Types of Arrays

In [92]:
#Get all zeros Numpy Array
np.zeros(5)
np.zeros((3,3,3))


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [97]:
# Get all ones Numpty Array
np.ones((2,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [99]:
# Get a all similar element array of specific number
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [102]:
# get an array of similar size of an exsiting array
c = np.full_like(a,5)
print(c)


[[5 5 5 5 5 5 5 5 5]
 [5 5 5 5 5 5 5 5 5]]


In [113]:
# Random Decimal numbers
np.random.rand(3,3)
np.random.random_sample(a.shape)

array([[0.13297332, 0.78071542, 0.55127009, 0.69425439, 0.70415478,
        0.50820952, 0.75152362, 0.50189133, 0.95683415],
       [0.76983509, 0.99117774, 0.89091763, 0.80727004, 0.88941407,
        0.29646389, 0.51647208, 0.4904684 , 0.64665405]])

In [114]:
# Random Integer numbers
np.random.randint(4,size=(3,3))

array([[3, 0, 2],
       [2, 3, 2],
       [3, 3, 0]])

In [116]:
# Random intger with start and finish
np.random.randint(-4,8,size=(3,3))

array([[-3, -3,  5],
       [-1,  7, -4],
       [ 5, -2,  3]])

In [117]:
# Indeitify Matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [122]:
#Repeating an Array
print(a)
print(np.repeat(a,3,axis=0))
print(np.repeat(a,3,axis=1))

[[ 1  2  3 13  5  6  7 15  9]
 [ 0  9  8 13  6  5  4  3  2]]
[[ 1  2  3 13  5  6  7 15  9]
 [ 1  2  3 13  5  6  7 15  9]
 [ 1  2  3 13  5  6  7 15  9]
 [ 0  9  8 13  6  5  4  3  2]
 [ 0  9  8 13  6  5  4  3  2]
 [ 0  9  8 13  6  5  4  3  2]]
[[ 1  1  1  2  2  2  3  3  3 13 13 13  5  5  5  6  6  6  7  7  7 15 15 15
   9  9  9]
 [ 0  0  0  9  9  9  8  8  8 13 13 13  6  6  6  5  5  5  4  4  4  3  3  3
   2  2  2]]


In [138]:
# New Task
z=np.ones((5,5),dtype='int32')
print(z)
z[1:-1,1:-1]=0
print(z)
z[2,2] =9
print(z)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Be careful when copying arrays

In [143]:
d = np.array([1,2,3])
print(d)
e=d
print(e)
e[0]=100
print(e)
print(d)

f= d.copy()
print(f)
f[0]=200
print(f)
print(d)

[1 2 3]
[1 2 3]
[100   2   3]
[100   2   3]
[100   2   3]
[200   2   3]
[100   2   3]


## Mathematics

In [144]:
g = np.array([1,2,3,4])
print(g)

[1 2 3 4]


In [146]:
g+2

array([3, 4, 5, 6])

In [147]:
g-2

array([-1,  0,  1,  2])

In [148]:
g*2

array([2, 4, 6, 8])

In [155]:
g/2

array([0.5, 1. , 1.5, 2. ])

In [156]:
g **2

array([ 1,  4,  9, 16])

In [158]:
np.sin(g)
np.cos(g)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [150]:
h = np.array([5,6,7,8])

In [151]:
g+h

array([ 6,  8, 10, 12])

In [152]:
g-h

array([-4, -4, -4, -4])

In [153]:
g*h

array([ 5, 12, 21, 32])

In [154]:
g/h

array([0.2       , 0.33333333, 0.42857143, 0.5       ])

### Linear Algebra

In [166]:
i = np.ones((2,3))
print(i)
j = np.full((3,2),2)
print(j)
print(np.matmul(i,j))
# Finding the determinant
print(np.identity(3))
np.linalg.det(np.identity(3))

# Determinant
#Trace
# Singular Vector Decompositoin
#Eigen values
# matrix Multiplication
# Inverse
# Etc...!

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]
[[6. 6.]
 [6. 6.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


1.0

## Statistics

In [173]:
np.min(g)
np.max(a,axis=1)

array([15, 13])

In [176]:
np.sum(a,axis=0)

array([ 1, 11, 11, 26, 11, 11, 11, 18, 11])

## Reorganising Array

In [182]:
print(a)
a.reshape(18,1)
a.reshape(1,18)

[[ 1  2  3 13  5  6  7 15  9]
 [ 0  9  8 13  6  5  4  3  2]]


array([[ 1,  2,  3, 13,  5,  6,  7, 15,  9,  0,  9,  8, 13,  6,  5,  4,
         3,  2]])

# Vertical staking
print(i)
print(j)
j.reshape(2,3)
np.vstack([i,j.reshape(2,3)])


In [193]:
# Horizontal Staking

print(i)
print(j)
np.hstack([j,i.reshape(3,2)])

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[2., 2., 1., 1.],
       [2., 2., 1., 1.],
       [2., 2., 1., 1.]])

## Miscellaneous

### Load Data from File

In [197]:
final_data = np.genfromtext('data.txt',delimiter=',')

AttributeError: module 'numpy' has no attribute 'genfromtext'

In [203]:
final_data = np.array([[1,2,3,4,5,6,7,8,9],[0,0,0,0,0,0,0,0,0],[9,8,7,6,5,4,3,2,1]])
print(final_data)
print(final_data.dtype)
final_data = final_data.astype('float32')
print(final_data.dtype)

[[1 2 3 4 5 6 7 8 9]
 [0 0 0 0 0 0 0 0 0]
 [9 8 7 6 5 4 3 2 1]]
int64
float32


### Boolaen Masking and Advanced Indexing

In [206]:
final_data >=5

array([[False, False, False, False,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False],
       [ True,  True,  True,  True,  True, False, False, False, False]])

In [208]:
final_data[final_data>=5]

array([5., 6., 7., 8., 9., 9., 8., 7., 6., 5.], dtype=float32)

In [212]:
print(np.any(final_data >=5,axis=1))
print(np.any(final_data >=5,axis=0))

[ True False  True]
[ True  True  True  True  True  True  True  True  True]


In [214]:
print(np.all(final_data >=5,axis=1))
print(np.all(final_data >=5,axis=0))

[False False False]
[False False False False False False False False False]


In [222]:
print(((final_data <= 5) & (final_data >= 3)))
print(~((final_data <= 5) & (final_data >= 3)))
print(((final_data <= 5) | (final_data >= 3)))

[[False False  True  True  True False False False False]
 [False False False False False False False False False]
 [False False False False  True  True  True False False]]
[[ True  True False False False  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True False False False  True  True]]
[[ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True]]


In [ ]:
numbers = range(1,31)
sequence_of_numbers = []
for number in numbers:
      sequence_of_numbers.append(number)

print(sequence_of_numbers)
a = np.copy(sequence_of_numbers)
print(a)
b = a.reshape(6,5)
print(b)
print(b[2:4,0:2])
print(b[[0,1,2,3],[1,2,3,4]])



## Scipy

In [253]:
import scipy
from scipy import cluster

In [254]:
help(cluster)

Help on package scipy.cluster in scipy:

NAME
    scipy.cluster

DESCRIPTION
    Clustering package (:mod:`scipy.cluster`)
    
    .. currentmodule:: scipy.cluster
    
    :mod:`scipy.cluster.vq`
    
    Clustering algorithms are useful in information theory, target detection,
    communications, compression, and other areas.  The `vq` module only
    supports vector quantization and the k-means algorithms.
    
    :mod:`scipy.cluster.hierarchy`
    
    The `hierarchy` module provides functions for hierarchical and
    agglomerative clustering.  Its features include generating hierarchical
    clusters from distance matrices,
    calculating statistics on clusters, cutting linkages
    to generate flat clusters, and visualizing clusters with dendrograms.

PACKAGE CONTENTS
    _hierarchy
    _optimal_leaf_ordering
    _vq
    hierarchy
    setup
    tests (package)
    vq

DATA
    __all__ = ['vq', 'hierarchy']

FILE
    /usr/local/anaconda/lib/python3.7/site-packages/scipy/cluster

In [256]:
scipy.info(cluster)

Clustering package (:mod:`scipy.cluster`)

.. currentmodule:: scipy.cluster

:mod:`scipy.cluster.vq`

Clustering algorithms are useful in information theory, target detection,
communications, compression, and other areas.  The `vq` module only
supports vector quantization and the k-means algorithms.

:mod:`scipy.cluster.hierarchy`

The `hierarchy` module provides functions for hierarchical and
agglomerative clustering.  Its features include generating hierarchical
clusters from distance matrices,
calculating statistics on clusters, cutting linkages
to generate flat clusters, and visualizing clusters with dendrograms.


## Special Fundtion Exp and Tri

In [261]:
from scipy import special
a= special.exp10(2)
print(a)
b=special.exp2(3)
print(b)
c= special.sindg(90)
print(c)

100.0
8.0
1.0


## Integration Functions

In [ ]:
from scipy import integrate


In [ ]:
i=scipy.integrate.quad(lambda x:special.exp10(10,0,1))
print(i)

e = lambda x,y: x*y**2
f = lambda x: 1
g = lambda x: -1
integrade.dblquad(e,0,2,f,g)

## Fourier Transformations

In [ ]:
from scipy.fftpack import fft, ifft
import numpy as np
x= np.array([1,2,3])
y = fft(x)
print(y)
z = ifft(x)
print(z)


## Linear Algebra

In [ ]:
from scipy import linalg
a= np.array([[1,2],[3,4]])
b= linalg.inv(a)
print(b)

## Interpolation Functions